#!/bin/sh -aeu
# Limit Discord using landlock-LSM backed sandbox.

# These environment variables *must* be defined:
#
# DBUS_SESSION_BUS_ADDRESS
# HOME
# WAYLAND_DISPLAY
# XDG_RUNTIME_DIR

# These environment variables *may* be defined:
#
# PIPEWIRE_CORE
# PIPEWIRE_RUNTIME_DIR
# PULSE_COOKIE
# PULSE_SERVER
# XDG_CACHE_HOME
# XDG_CONFIG_HOME
# XDG_DATA_HOME
# XDG_DOWNLOAD_DIR

# Set XDG_* early as it is often referenced. XDG_RUNTIME_DIR must already exist!
XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
XDG_DOWNLOAD_DIR="${XDG_DOWNLOAD_DIR:-$HOME/Downloads}"

# A seperate temporary directory significantly decreases runtime attack-surface.
rundir="${XDG_RUNTIME_DIR}/landlock/discord-${$}"
mkdir -p "$rundir"

# A dbus proxy significantly decreases runtime attack-surface.
dbus_proxy="${rundir}/bus"
xdg-dbus-proxy "$DBUS_SESSION_BUS_ADDRESS" "$dbus_proxy"	\
--filter							\
--broadcast=org.freedesktop.portal.*=@/org/freedesktop/portal/*	\
--call=org.freedesktop.portal.*=*				\
--own=org.mpris.MediaPlayer2.discord.*				\
--talk=ca.desrt.dconf						\
--talk=org.a11y.Bus						\
--talk=org.gtk.Settings						\
--talk=org.kde.StatusNotifierWatcher				\
&

# TODO: check for proxy readiness directly (see --fd in xdg-dbus-proxy(1)).
sleep 1
DBUS_SESSION_BUS_ADDRESS="unix:path=${dbus_proxy}"

# Pipewire (for screencast).
PIPEWIRE_CORE="${PIPEWIRE_CORE:-pipewire-0}"
PIPEWIRE_RUNTIME_DIR="${PIPEWIRE_RUNTIME_DIR:-$XDG_RUNTIME_DIR}"

# Pulseaudio (for audio).
PULSE_COOKIE="${PULSE_COOKIE:-$XDG_CONFIG_HOME/pulse/cookie}"

# TODO: support ipv6 with custom port.
case "${PULSE_SERVER:=unix:$XDG_RUNTIME_DIR/pulse/native}" in
unix:*)
	# This port will never be assigned.
	pulse_port=0

	pulse_proxy="${PULSE_SERVER#*:}"

	;;

tcp:*)
	if [ "${PULSE_SERVER%:*}" = tcp ]
	then

	# No port. Use the default.
	pulse_port=4317

	else

	pulse_port="${PULSE_SERVER##*:}"

	fi

	# This directory will always be readable.
	pulse_proxy="$rundir"

	;;

*)
	# BAD FORMAT!
	unset PULSE_SERVER

	# This port will never be assigned.
	pulse_port=0

	# This directory will always be readable.
	pulse_proxy="$rundir"

	;;
esac

# Wayland (for display).
WAYLAND_DISPLAY="${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}"

# Read-only paths
LL_FS_RO="/bin/bash:/etc/fonts:/etc/gtk-3.0:/etc/ld.so.cache:/etc/mime.types:/etc/resolv.conf:/etc/ssl/certs/ca-certificates.crt:/lib:/lib64:/opt/discord:/sys/bus:/sys/class:/sys/devices:/usr/bin/discord:/usr/bin/env:/usr/bin/xdg-mime:/usr/lib:/usr/lib64:/usr/share:/var/cache/fontconfig:${PULSE_COOKIE}:${XDG_CONFIG_HOME}/Electron:${XDG_CONFIG_HOME}/chromium"

# Read-write paths
# TODO: https://github.com/flatpak/xdg-desktop-portal/issues/27#issuecomment-233057825
LL_FS_RW="/dev:/proc:${HOME}/.pki:${PIPEWIRE_RUNTIME_DIR}/${PIPEWIRE_CORE}:${XDG_CACHE_HOME}/fontconfig:${XDG_CACHE_HOME}/mesa_shader_cache:${XDG_CACHE_HOME}/mesa_shader_cache_db:${XDG_CONFIG_HOME}/discord:${XDG_DOWNLOAD_DIR}/discord:${WAYLAND_DISPLAY}:${dbus_proxy}:${pulse_proxy}:${rundir}"

# Bindable ports (for server programs)
LL_TCP_BIND="6463"

# Connectable ports (for client programs)
# TODO: document that WebRTC will fail if regional server port is blocked.
LL_TCP_CONNECT="80:443:2083:2096:8443:${pulse_port}"

# These environment variables are intentionally set after LL_* .
TMPDIR="$rundir"
XDG_RUNTIME_DIR="$rundir"

# Cleanup dbus-proxy on exit.
trap "kill ${!} ; rm -r $rundir" EXIT INT

# Cleanup setup environment.
unset dbus_proxy
unset pulse_port
unset pulse_proxy
unset rundir

# Avoid exec(1) for trap(1) to work.
sandboxer discord "$@"
